// <auto-generated />
using System;
using BlazorWasmCustomerProject.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BlazorWebbAsemblyAppCustomer.Server.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20221201211402_initial")]
    partial class initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BlazorWebbAsemblyApp_Customer.Shared.Customer", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CompanyName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContactName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PostalCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Region")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Gianni Chalkidi",
                            City = "Thessaloniki",
                            CompanyName = "Deloitte",
                            ContactName = "Michalis",
                            Country = "Greece",
                            Phone = "6845210369",
                            PostalCode = "54249",
                            Region = "Charilaou"
                        },
                        new
                        {
                            Id = 2,
                            Address = "Konstantinoupoleos",
                            City = "Thessaloniki",
                            CompanyName = "Eastern Young",
                            ContactName = "Pavlos",
                            Country = "Greece",
                            Phone = "6981234567",
                            PostalCode = "55231",
                            Region = "Toumpa"
                        },
                        new
                        {
                            Id = 3,
                            Address = "Pavlou Mela",
                            City = "Athens",
                            CompanyName = "Epsilon net",
                            ContactName = "Eleni",
                            Country = "Greece",
                            Phone = "6984561238",
                            PostalCode = "55242",
                            Region = "Ampelokipoi"
                        },
                        new
                        {
                            Id = 4,
                            Address = "Papanastasiou",
                            City = "Larisa",
                            CompanyName = "Alpha net",
                            ContactName = "Aleksandra",
                            Country = "Greece",
                            Phone = "6978945612",
                            PostalCode = "57470",
                            Region = "Kentro"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
